In [1]:
DIMS = (18,11)

In [2]:
import numpy as np
climbs = np.loadtxt('datasets/climbs.txt')
climbs

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [3]:
climbs.shape

(214308, 11)

In [4]:
def flattenClimbs(data, rows):
    arrs = []
    for i in range(rows):
        arrs.append(data[range(i, data.shape[0], rows)])
    return(np.concatenate(arrs, axis=1))

In [5]:
flattened = flattenClimbs(climbs, DIMS[0]).astype(int)
flattened

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [6]:
flattened.shape

(11906, 198)

In [7]:
import csv
f = open('datasets/flattenedClimbs.csv',"w")
f.truncate()
writer = csv.writer(f)
for row in flattened:
    writer.writerow(row)
f.close()

In [8]:
import pandas as pd
cols = []
for i in range(DIMS[0]):
    for j in range(DIMS[1]):
        cols.append((i,j))
df = pd.DataFrame(flattened, columns=cols).astype(bool)
df

(0, 0)  (0, 1)  (0, 2)  (0, 3)  (0, 4)  (0, 5)  (0, 6)  (0, 7)  (0, 8)  \
0       False   False    True   False   False   False   False   False   False   
1       False   False   False   False    True   False   False   False   False   
2       False   False   False   False   False   False    True   False   False   
3       False   False   False    True   False   False   False   False   False   
4       False   False   False   False   False   False   False   False    True   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
11901   False   False   False   False   False   False    True   False   False   
11902   False   False   False   False   False   False   False    True   False   
11903   False   False   False   False   False   False   False   False    True   
11904   False   False   False   False   False   False   False   False   False   
11905   False   False   False   False   False   False    True   False   False   

       (0, 9)  ...  (17, 1)  (17, 2)  (17, 3)  (17, 4)  (17, 5)  (17, 6)  \
0       False  ...    False    False    False    False    False    False   
1       False  ...    False    False    False    False    False    False   
2       False  ...    False    False    False    False    False    False   
3       False  ...    False    False    False    False    False    False   
4       False  ...    False    False    False    False    False    False   
...       ...  ...      ...      ...      ...      ...      ...      ...   
11901   False  ...    False    False    False    False    False    False   
11902   False  ...    False    False    False    False    False    False   
11903   False  ...    False    False    False    False    False    False   
11904   False  ...    False    False    False    False    False    False   
11905   False  ...    False    False    False    False    False    False   

       (17, 7)  (17, 8)  (17, 9)  (17, 10)  
0        False    False    False     False  
1        False    False    False     False  
2        False    False    False     False  
3        False    False    False     False  
4        False    False    False     False  
...        ...      ...      ...       ...  
11901    False    False    False     False  
11902    False    False    False     False  
11903    False    False    False     False  
11904    False    False    False     False  
11905    False    False    False     False  

[11906 rows x 198 columns]

In [9]:
df['holds'] = df.apply(lambda row: row[row].index, axis=1)
df

(0, 0)  (0, 1)  (0, 2)  (0, 3)  (0, 4)  (0, 5)  (0, 6)  (0, 7)  (0, 8)  \
0       False   False    True   False   False   False   False   False   False   
1       False   False   False   False    True   False   False   False   False   
2       False   False   False   False   False   False    True   False   False   
3       False   False   False    True   False   False   False   False   False   
4       False   False   False   False   False   False   False   False    True   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
11901   False   False   False   False   False   False    True   False   False   
11902   False   False   False   False   False   False   False    True   False   
11903   False   False   False   False   False   False   False   False    True   
11904   False   False   False   False   False   False   False   False   False   
11905   False   False   False   False   False   False    True   False   False   

       (0, 9)  ...  (17, 2)  (17, 3)  (17, 4)  (17, 5)  (17, 6)  (17, 7)  \
0       False  ...    False    False    False    False    False    False   
1       False  ...    False    False    False    False    False    False   
2       False  ...    False    False    False    False    False    False   
3       False  ...    False    False    False    False    False    False   
4       False  ...    False    False    False    False    False    False   
...       ...  ...      ...      ...      ...      ...      ...      ...   
11901   False  ...    False    False    False    False    False    False   
11902   False  ...    False    False    False    False    False    False   
11903   False  ...    False    False    False    False    False    False   
11904   False  ...    False    False    False    False    False    False   
11905   False  ...    False    False    False    False    False    False   

       (17, 8)  (17, 9)  (17, 10)  \
0        False    False     False   
1        False    False     False   
2        False    False     False   
3        False    False     False   
4        False    False     False   
...        ...      ...       ...   
11901    False    False     False   
11902    False    False     False   
11903    False    False     False   
11904    False    False     False   
11905    False    False     False   

                                                   holds  
0      Index([(0, 2), (2, 6), (5, 5), (9, 7), (11, 1)...  
1      Index([(0, 4), (4, 0), (7, 3), (10, 2), (14, 6...  
2      Index([ (0, 6),  (3, 4),  (5, 6),  (7, 4),  (9...  
3      Index([(0, 3), (2, 4), (5, 2), (8, 7), (10, 4)...  
4      Index([(0, 8), (4, 10), (7, 3), (9, 8), (11, 8...  
...                                                  ...  
11901  Index([(0, 6), (3, 3), (6, 4), (8, 4), (10, 9)...  
11902  Index([(0, 7), (2, 3), (5, 3), (7, 4), (13, 5)...  
11903  Index([  (0, 8),   (2, 9),   (3, 4),   (3, 8),...  
11904  Index([ (0, 10),   (2, 9),   (3, 4),   (3, 8),...  
11905  Index([(0, 6), (1, 6), (3, 0), (6, 4), (10, 3)...  

[11906 rows x 199 columns]

In [10]:
df.loc[0,'holds']

Index([(0, 2), (2, 6), (5, 5), (9, 7), (11, 1), (11, 6), (16, 9)], dtype='object')

In [11]:
grades = np.loadtxt('datasets/grades.txt')
grades

array([12.,  5.,  4., ...,  5.,  5., 12.])

In [12]:
grades.shape

(11906,)