In [1]:
DIMS = (18,11)

In [2]:
import numpy as np
climbs = np.loadtxt('datasets/climbs.txt')
climbs

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [3]:
climbs.shape

(214308, 11)

In [4]:
def flattenClimbs(data, rows):
    arrs = []
    for i in range(rows):
        arrs.append(data[range(i, data.shape[0], rows)])
    return(np.concatenate(arrs, axis=1))

In [5]:
flattened = flattenClimbs(climbs, DIMS[0]).astype(int)
flattened

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [6]:
flattened.shape

(11906, 198)

In [7]:
import csv
f = open('datasets/flattenedClimbs.csv',"w")
f.truncate()
writer = csv.writer(f)
for row in flattened:
    writer.writerow(row)
f.close()

In [8]:
# import pandas as pd
# cols = []
# for i in range(DIMS[0]):
#     for j in range(DIMS[1]):
#         cols.append((i,j))
# pd.DataFrame(flattened, columns=cols)

In [9]:
grades = np.loadtxt('datasets/grades.txt')
grades

array([12.,  5.,  4., ...,  5.,  5., 12.])

In [10]:
grades.shape

(11906,)

In [11]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(flattened, grades)

In [12]:
clf.predict([flattened[0,:]])

array([12.])

In [ ]:
tree.plot_tree(clf)

[Text(282.479463592329, 216.06379746835444, 'X[148] <= 0.5\ngini = 0.834\nsamples = 11906\nvalue = [1, 3643, 1214, 1693, 1617, 1384, 666, 752, 529, 232\n104, 24, 17, 30]'),
 Text(242.12710993842123, 213.3113924050633, 'X[61] <= 0.5\ngini = 0.868\nsamples = 8180\nvalue = [0, 1677, 828, 1183, 1248, 1151, 592, 653, 487, 212\n94, 18, 15, 22]'),
 Text(226.5497153320183, 210.55898734177214, 'X[114] <= 0.5\ngini = 0.873\nsamples = 7460\nvalue = [0, 1308, 761, 1077, 1182, 1097, 578, 628, 474, 208\n94, 18, 15, 20]'),
 Text(208.7597119857675, 207.80658227848102, 'X[119] <= 0.5\ngini = 0.877\nsamples = 6637\nvalue = [0, 1037, 633, 918, 1072, 1014, 548, 608, 461, 203\n91, 18, 15, 19]'),
 Text(196.1594911897204, 205.05417721518987, 'X[95] <= 0.5\ngini = 0.879\nsamples = 6125\nvalue = [0, 850, 553, 830, 999, 971, 537, 599, 448, 197, 90\n18, 14, 19]'),
 Text(184.74751427970602, 202.30177215189872, 'X[37] <= 0.5\ngini = 0.88\nsamples = 5563\nvalue = [0, 682, 469, 731, 906, 908, 519, 574, 442, 194, 89\